### ISSUE TITLE
No module named monet.models

### ISSUE THREAD

**Issue by lambertaa** [noaa-oar-arl/monet#95]
I am just getting started with using your library and began with the tutorial. In your tutorial you have:

import xarray as xr
import monet as m

cmaqfile = monet.__path__ + '/../data/aqm.t12z.aconc.ncf'

from monet.models import cmaq

c = cmaq.open_dataset(cmaqfile)

However, there is no monet.models in my package files for monet. I can't see any evidence that the cmaq module is stored anywhere here. Using help(monet) produces:

NAME
    monet

PACKAGE CONTENTS
    met_funcs
    monet_accessor
    plots (package)
    util (package)

I am wondering why I have lost this module in my install. Is this due to an update of monet? Is there a previous version that I should install instead? Or do you think it might be a problem with my dependencies somehow?

**Comment by bbakernoaa** [comment]
Hi @lambertaa yes was due to an update.  MONET was split into two repositories, MONET and MONETIO.  MONETIO is the I/O portion of MONET which was previously part of MONET before version 2.2.  MONETIO is available at [https://github.com/noaa-oar-arl/monetio](https://github.com/noaa-oar-arl/monetio).  

To use it you would follow the same tutorial as the MONET tutorial but you would use monetio for the I/O portion of the tutorial.

```python

import monet as m
import monetio as mio

cmaqfile = mio.path + '/../data/aqm.t12z.aconc.ncf'

c = mio.cmaq.open_dataset(cmaqfile)

```

Sorry about the readthedocs.  I need to update them but have been pulled to get some other funded projects going.  

FYI.  You can use MONET on any xarray and pandas object as MONET is just an extension of those libraries (ie the accessor).

**Comment by lambertaa** [comment]
@bbakernoaa perfect, thank you! No worries about the readthedocs. monetio.readthedocs.io has been helpful now that I know where to find it. Appreciate the quick response.

**Comment by bbakernoaa** [comment]
@lambertaa Sure.  Any other issues please feel free to post issues.  Someone will try and help out.
